name: HelloWorldTestingDocument
description: This is hello world testing document.
schemaVersion: 1.0

phases:
  - name: test
    steps:
      - name: HelloWorldStep
        action: ExecuteBash
        inputs:
          commands:
            - echo "Hello World! Test."
            - cd '/opt'
            - sudo useradd factorio
            - export PATH=/home/ubuntu/.local/bin:$PATH
            - git clone https://github.com/narc0tiq/factorio-updater.git
            - git clone https://github.com/RynoXLI/factorio-init.git
            - sudo /opt/factorio-init/factorio install
            - echo "source /opt/factorio-init/bash_autocomplete" >> ~/.bashrc
            - sudo ln -s /opt/factorio-init/factorio /usr/local/bin/factorio
            - sudo cp /opt/factorio-init/factorio.service.example /etc/systemd/system/factorio.service
            - sudo systemctl daemon-reload
            - sudo ln -s /opt/factorio-init/factorio /etc/init.d/factorio
            - sudo chmod +x /opt/factorio-init/factorio
            - sudo (crontab -l ; echo "10 * * * * bash /opt/factorio-init/sync.sh") | crontab
